### ISSUE TITLE
Test Parameters

### ISSUE THREAD

**Issue by ebisbe** [jordisala1991/sermepa-omnipay#1]
Hello Jordi,

I have no idea what parameters I'm missing to set up test environment. My current params are:

'titular' => '327234688',
				'consumerLanguage' => '001',
				'currency' => '978',
				'terminal' => '002',
				'merchantURL' => 'https://sis-t.redsys.es:25443/sis/realizarPago',
				'merchantName' => '327234688',
				'merchantKey' => 'qwertyasdf0123456789',
				'transactionType' => '0',
				'signatureMode' => 'simple',
				'testMode' => true

Thanks

**Comment by jordisala1991** [comment]
El parametro de titular no es necesario que lo mandes, el consumer language currency y terminal los puedes mandar tal y como lo haces. El signature mode tampoco es necesario.

Para crear el gateway:

'consumerLanguage' => '001',
'merchantName' => 'Nombre de la tienda/empresa',
'merchantCode' => '327234688',
'merchantKey' => 'qwertyasdf0123456789',
'merchantURL' => 'url de notificación online (implementada por ti)',
'testMode' => true,

Para enviar un pago:

'returnUrl' => 'url de ok de tu tienda',
'cancelUrl' => 'url de ko de tu tienda',
'amount' => ,
'description' => 'Descripción de la compra',
'token' => 'Identificador único de compra',

La cantidad es un poco especial, la tienes que multiplicar por 100, pero aún así la tienes que convertir a float.

Lo intentare documentar en el readme. Espero que te sirva

**Comment by ebisbe** [comment]
He añadido merchantURl -> 'www.domain.dev/checkout'

En la parte de pago ya tenia returnUrl, cancelUrl y amount. He añadido description y el token. 

Me continua fallando y me da este error 

ErrorException in Encryptor.php line 18: mcrypt_encrypt(): Key of size 15 not supported by this algorithm. Only keys of size 24 supported

**Comment by jordisala1991** [comment]
Prueba este merchant key: sq7HjrUOBfKmC576ILgskD5srU870gJ7

**Comment by ebisbe** [comment]
Con ese merchant key me funciona. De donde lo has sacado?

Me da este error sermepa:

Importe 0  Sin Asignar

He repasado y estoy enviado mi valor 27.21 -> 2721 en float. 

Alguna idea??

**Comment by jordisala1991** [comment]
El merchant key que te he pasado es el del entorno de test de sermepa. El que siempre me dan ellos para testear.

El amount lo tienes que pasar como string '2721.00'

**Comment by ebisbe** [comment]
En su documentacion tengo otro valor... 
No me deja enviarlo com string:

InvalidRequestException in AbstractRequest.php line 299: String is not a valid decimal number.

```
in AbstractRequest.php line 299
at AbstractRequest->toFloat(**'2,721.00'**) in AbstractRequest.php line 325
at AbstractRequest->getAmount() in PurchaseRequest.php line 91
at PurchaseRequest->getData() in AbstractRequest.php line 673
```
